// Code generated by mockery v2.10.4. DO NOT EDIT.

package mocks

import (
	context "context"

	dto "git.garena.com/sea-labs-id/bootcamp/batch-03/maulana-jaelani/exercise-job-application-rest-api/dto"
	mock "github.com/stretchr/testify/mock"
)

// AppicantRecordService is an autogenerated mock type for the AppicantRecordService type
type AppicantRecordService struct {
	mock.Mock
}

// AppliedJob provides a mock function with given fields: ctx, AppicantRecord
func (_m *AppicantRecordService) AppliedJob(ctx context.Context, AppicantRecord dto.AppliedReq) (*dto.ApplicantRecord, error) {
	ret := _m.Called(ctx, AppicantRecord)

	var r0 *dto.ApplicantRecord
	if rf, ok := ret.Get(0).(func(context.Context, dto.AppliedReq) *dto.ApplicantRecord); ok {
		r0 = rf(ctx, AppicantRecord)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.ApplicantRecord)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, dto.AppliedReq) error); ok {
		r1 = rf(ctx, AppicantRecord)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
